repos:
  - repo: https://github.com/jupblb/pre-commit-pandoc
    rev: v1.0.0
    hooks:
      - id: pandoc
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write --ignore-unknown
        language: system
        files: \.(js|jsx|ts|tsx|css|less|html)$
        exclude: ^(dist/|node_modules/)
